### ISSUE TITLE
Get ALL companys from vincere API...

### ISSUE THREAD

**Issue by birdietorerik** [vincere-io/vincere-identity#2]
Hi!

I am working on a project that are getting job information from vincere API.
But strugle to get ALL jobs from this URL:

****https://nordicjobsworldwide.vincere.io/api/v2/job/search/fl=id,location,job_title,created_date,industry,fe;mlt.fl=industry_id,fe_id;sort=created_date asc?q=id:28954%23&start=0****

I am using Postman to test the API call, with id-token and api-key in the header information

It returns this in Postman ?

"result": {
        "start": 0,
        "total": 0,
        "items": []
    },
    "category": "job"

What do i do wrong ?

**Comment by vincere-developer** [comment]
Hi,

Your query is not retrieving all jobs. q=id:28954 means you are finding a job with id=28954. Retrieving all jobs don't need any query or filter.

Please read document carefully (I instructed how to construct query for search). Your API documentation is here:

https://nordicjobsworldwide.vincere.io/ext/v2/documentation.html

For each search section I included example, but note that example is still example. You should not copy it unless you know what it means. 

Besides this place is for Vincere Identity. For Vincere APIs questions, please post to https://github.com/vincere-io/restful-api-support/issues. 

Please let me know if you have any concerns.

**Comment by vincere-developer** [comment]
I close this issue because it's invalid.
