### ISSUE TITLE
Invalid Client ID

### ISSUE THREAD

**Issue by meinhard-meintjes** [vincere-io/vincere-identity#5]
Hi guys,

I'm trying to integrate your API with a clients website. I'm using the client ID that I generated in the Vincere App -> settings -> Marketplace -> API tab. For this I'm following the exact steps you portrayed in the README but all I get is the following error:
`{"error":"invalid_client"}`

My URL looks something like this:
`https://id.vincere.io/oauth2/authorize?response_type=code&redirect_uri=[redirect_uri]t&client_id=[my_client_id]`

Could it be an issue because I'm programming and testing this locally (domain: http://www.example.local/)? I did add this as a callback URL, just a different route.

Another question I have is what the API key is for - does it represent the typical "client_secret"?

I would appreciate your help. Thank you.

Kind regards

**Comment by meinhard-meintjes** [comment]
The issue was that the callback URL was URL encoded, which isn't allowed - it must be exactly the same.

**Comment by MazEbeid** [comment]
@meinhard-meintjes Hi could you please elaborate more on how were you testing this locally. I have been trying to get this to authenticate but with no luck. I am using hook.io (webhook) as my callback url - I was expecting to see the login page but I keep getting a 404 error. I would like to try and test it on my local machine but I dont know how.

Your help is appreciated, thanks

**Comment by meinhard-meintjes** [comment]
Hi @MazEbeid  , sorry I was offline for a week now... In case you're still having trouble with this:

Local testing is no problem. You just need to change the callback URL in Vincere to your exact, unencoded local callback URL. I'm not sure how your hook.io flow looks, though, so I can't help there right now. A 404 doesn't sound right. You need to log in using (GET) "https://id.vincere.io/oauth2/authorize?client_id=123456&state=STATE&redirect_uri=https://YOUR_APP/redirect_uri&response_type=code" and even if you use that dummy link you don't get a 404 (as you stated in your issue, there is also a testing endpoint you can use). Your redirect URL should be a URL in your software where you'll capture the AUTHORIZATION_CODE and call "https://id.vincere.io/oauth2/token" (POST) to receive your actual token. Only after that you use "https://[yourcompany].vincere.io/api/v2/".

Hope that helps...

**Comment by MazEbeid** [comment]
Hi @meinhard-meintjes 

Thanks for your help. I have actually decided to drop the platform as they weren't helpful on several occasions.
