### ISSUE TITLE
Can't authorized to access API

### ISSUE THREAD

**Issue by MazEbeid** [vincere-io/vincere-identity#6]
I have been trying to connect to the API but with no success.
I have followed the steps found on the API documentation. https://vincere.io/documentation.html

1- created an api key v2
2- created a client id
3- pasted callback url -(I think the problem might be here, I have a google script published as a web app that I am using just for testing, it doesn't contain anything, I have also tried to use a webhook for my callbackUrl but with no luck)

https://"Mydomain".io/oauth2/authorize?client_id="MyClientID"&state=STATE&redirect_uri=https://script.google.com/macros/s/AKfycbw8VVWhuKWepdGU29vJk03RnjJksor3BN6JRU4wx-AinGIaMtvE/exec&response_type=code

I was hoping that although that my web app is not listening to  POST requests the above GET request would redirect me to the Vincere portal to enter my username and password and then reply with the required info to my callbackUrl.

When I try the above GET request I get a 404 error and the page says that this should have not happened.

Appreciate your assistance on this

**Comment by mrbkiter** [comment]
Hi @MazEbeid 

I am afraid that https://"Mydomain".io/oauth2/authorize is a wrong Identity URL. For Vincere we only have id.vincere.io and id.vinceredev.com for prod and test env respectively. 

Please try again with id.vincere.io, and let me know the result.

**Comment by MazEbeid** [comment]
Hi @mrbkiter  thanks for your response.

I have actually dropped the whole service as I wasn't getting enough support with this.

The reason why I used Mydomain.Vincere.io/.... is because your colleague advised me to do so because I was using the id.vincere... and I was getting invalid client id error.

Find below your colleagues email 

Sent on 

Below is an example of the format we have used in our GET request with our current callbackUrl and clientId.

 https://id.vincere.io/oauth2/authorizeclient_id=b3df61e8-2734-41f5-9756-fcf63fa3c93e&state=STATE&redirect_uri=https://script.google.com/macros/s/AKfycbw8VVWhuKWepdGU29vJk03RnJksor3BN6JRU4wxAinGIaMtvE/exec&response_type=code

Appreciate your assistance.

Recieved on August 8

Hi Mazen,

The URL should be the vincere link of Saif. It should be https://holdenknight.vincere.io instead of https://id.vincere.io 

Can you test that please?

Best,
Marlon

**Comment by mrbkiter** [comment]
Hi @MazEbeid 

I'm sorry to hear your drop. We were busy for new release last week, so I forgot responding to your question. 

The guide from our support team was incorrect. Possibly he misunderstood the API endpoints for v2 and the centralized URL for Vincere Identity for all. 

For your case, I checked from your config, it should have been something like this:

https://id.vincere.io/oauth2/authorize?client_id=fb013a9c-f96c-4267-a157-02767810b631&response_type=code&redirect_uri=http://elbateekh.localtunnel.me/vincere

As you see, the redirect url should be the one I entered in API config section. Now if you copy, and paste to browser, it would navigate you to login form. You would need to input username/password, and then follow next steps to receive id-token and refresh-token.

In case you need any help, just drop a message. Hopefully we would see you back to Vincere in future.
