### ISSUE TITLE
Missing Authentication Token error for /oauth2/authorize

### ISSUE THREAD

**Issue by alexeytwolinkme** [vincere-io/vincere-identity#8]
Hi,

I get HTTP status code `403 Forbidden` with the following error message when calling `/oauth2/authorize`
```
{
    "message": "Missing Authentication Token"
}
```

What I've done:
1. Generated Vincere API token
2. Generated Client ID
3. Pasted Callback URL

Then I called the following:
1. id.vincere.io with `x-api-key` header
`curl -X GET -H "x-api-key: MY_API_TOKEN" https://id.vincere.io/api/v2/oauth2/authorize?client_id=MY_CLIENT_ID&response_type=code&redirect_uri=MY_CALLBACK_URL&state=MY_STATE`
2. id.vinceredev.com with `x-api-key` header
`curl -X GET -H "x-api-key: MY_API_TOKEN" https://id.vinceredev.com/api/v2/oauth2/authorize?client_id=MY_CLIENT_ID&response_type=code&redirect_uri=MY_CALLBACK_URL&state=MY_STATE`
3. id.vincere.io without `x-api-key` header
`curl -X GET https://id.vincere.io/api/v2/oauth2/authorize?client_id=MY_CLIENT_ID&response_type=code&redirect_uri=MY_CALLBACK_URL&state=MY_STATE`
4. id.vinceredev.com without `x-api-key` header
`curl -X GET https://id.vinceredev.com/api/v2/oauth2/authorize?client_id=MY_CLIENT_ID&response_type=code&redirect_uri=MY_CALLBACK_URL&state=MY_STATE`

All the above return  `403 Forbidden`.

N.B.
I also tried sending `Authorization` header and the errors change. Which means Vincere API does process `Authorization` header.

Please advise. If `Authorization` header is required, what value should be provided for it?

Thanks!

Alex

**Comment by phamvannam** [comment]
Hi @alexeytwolinkme 
I think your link you put incorrect.
can you change:
https://id.vinceredev.com/api/v2/oauth2/authorize?
to
https://id.vincere.io/oauth2/authorize?
here is documentation: https://github.com/vincere-io/vincere-identity
Good luck,

**Comment by alexeytwolinkme** [comment]
Hi @phamvannam 
My bad. As usual, user error. Thank you for your response. It works now. Had /api/v2 left in the URL by mistake from other Vincere calls.
